import { useState, useEffect } from "react";
import { supabase } from "./supabase";

const SERVICES = ["EMS", "Bota de Compressão", "Banheira de Gelo", "Raio-X do Jogo"];
const LOCATIONS = ["In Home", "Racquet Club Terral", "Racquet Club Salve Arena"];
const STAGES = ["Lead", "Contato feito", "FUP", "Avaliação agendada", "Cliente ativo", "Inativo"];
const COLORS = {"Lead":"#c9a96e","Contato feito":"#1a3545","FUP":"#b05e1a","Avaliação agendada":"#2a6b8a","Cliente ativo":"#2d7a4f","Inativo":"#888"};
const gold="#c9a96e",navy="#0C1B33",cream="#F5F0E8";
const E0={name:"",phone:"",email:"",birthday:"",stage:"Lead",location:"In Home",services:[],notes:"",attendances:[],tasks:[],touchpoints:[]};
function locLabel(l){return l==="In Home"?"🏠 In Home":l==="Racquet Club Terral"?"🎾 Terral":"🎾 Salve Arena"}
function Badge({stage}){return <span style={{background:COLORS[stage]+"22",color:COLORS[stage],border:"1px solid "+COLORS[stage]+"55",borderRadius:20,padding:"2px 10px",fontSize:12,fontWeight:600}}>{stage}</span>}
function Modal({title,onClose,children,wide}){return(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.55)",zIndex:100,display:"flex",alignItems:"center",justifyContent:"center",padding:16}}><div style={{background:cream,borderRadius:14,width:"100%",maxWidth:wide?780:620,maxHeight:"93vh",overflowY:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"18px 24px 14px",borderBottom:"1px solid #e0d8cc"}}><span style={{fontWeight:700,fontSize:17,color:navy}}>{title}</span><button onClick={onClose} style={{background:"none",border:"none",fontSize:20,cursor:"pointer"}}>✕</button></div><div style={{padding:"20px 24px 24px"}}>{children}</div></div></div>);}
function Inp({label,value,onChange,type="text",placeholder=""}){return(<div style={{marginBottom:13}}>{label&&<label style={{display:"block",fontSize:12,fontWeight:600,marginBottom:4}}>{label}</label>}<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} style={{width:"100%",padding:"8px 12px",border:"1px solid #c9b89a",borderRadius:8,fontSize:14,background:"#fffdf8",boxSizing:"border-box",outline:"none"}}/></div>);}
function Sel({label,value,onChange,options}){return(<div style={{marginBottom:13}}>{label&&<label style={{display:"block",fontSize:12,fontWeight:600,marginBottom:4}}>{label}</label>}<select value={value} onChange={e=>onChange(e.target.value)} style={{width:"100%",padding:"8px 12px",border:"1px solid #c9b89a",borderRadius:8,fontSize:14,background:"#fffdf8",boxSizing:"border-box",outline:"none"}}>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></div>);}
function TA({label,value,onChange,rows=3}){return(<div style={{marginBottom:13}}>{label&&<label style={{display:"block",fontSize:12,fontWeight:600,marginBottom:4}}>{label}</label>}<textarea value={value} onChange={e=>onChange(e.target.value)} rows={rows} style={{width:"100%",padding:"8px 12px",border:"1px solid #c9b89a",borderRadius:8,fontSize:14,background:"#fffdf8",boxSizing:"border-box",outline:"none",resize:"vertical"}}/></div>);}
function MC({label,options,selected,onChange}){return(<div style={{marginBottom:13}}>{label&&<label style={{display:"block",fontSize:12,fontWeight:600,marginBottom:6}}>{label}</label>}<div style={{display:"flex",flexWrap:"wrap",gap:8}}>{options.map(o=><button key={o} onClick={()=>onChange(selected.includes(o)?selected.filter(x=>x!==o):[...selected,o])} style={{padding:"5px 12px",borderRadius:20,border:"1px solid",borderColor:selected.includes(o)?gold:"#c9b89a",background:selected.includes(o)?gold+"22":"#fffdf8",fontSize:13,cursor:"pointer",fontWeight:selected.includes(o)?600:400}}>{o}</button>)}</div></div>);}
function Tabs({tabs,active,onChange}){return(<div style={{display:"flex",gap:4,borderBottom:"2px solid #e0d8cc",marginBottom:18}}>{tabs.map(t=><button key={t.id} onClick={()=>onChange(t.id)} style={{padding:"8px 16px",border:"none",background:"none",cursor:"pointer",fontWeight:active===t.id?700:400,fontSize:13,color:active===t.id?navy:"#888",borderBottom:active===t.id?"2px solid "+navy:"2px solid transparent",marginBottom:-2}}>{t.label}</button>)}</div>);}

export default function CRM(){
  const [clients,setClients]=useState([]);
  const [search,setSearch]=useState("");
  const [fs,setFs]=useState("Todos");
  const [view,setView]=useState("list");
  const [modal,setModal]=useState(null);
  const [sel,setSel]=useState(null);
  const [tab,setTab]=useState("geral");
  const [form,setForm]=useState(E0);
  const [af,setAf]=useState({date:"",service:"",professional:"",notes:"",duration:""});
  const [tf,setTf]=useState({title:"",dueDate:"",reminder:"",done:false});
  const [pf,setPf]=useState({date:"",channel:"WhatsApp",direction:"Entrada",summary:""});
  const [loading,setLoading]=useState(true);
  const [sub,setSub]=useState(null);

  useEffect(()=>{(async()=>{const{data}=await supabase.from("clients").select("*").order("created_at",{ascending:false});if(data)setClients(data);setLoading(false);})();},[]);

  const upsert=async()=>{if(form.id){const{data}=await supabase.from("clients").update({...form}).eq("id",form.id).select();if(data)setClients(p=>p.map(c=>c.id===form.id?data[0]:c));}else{const{data}=await supabase.from("clients").insert([{...form,attendances:[],tasks:[],touchpoints:[]}]).select();if(data)setClients(p=>[data[0],...p]);}setModal(null);};
  const del=async id=>{await supabase.from("clients").delete().eq("id",id);setClients(p=>p.filter(c=>c.id!==id));setModal(null);};
  const upd=async fn=>{const u=fn(sel);const{data}=await supabase.from("clients").update(u).eq("id",sel.id).select();if(data){setClients(p=>p.map(c=>c.id===sel.id?data[0]:c));setSel(data[0]);}};
  const mv=async(id,stage)=>{await supabase.from("clients").update({stage}).eq("id",id);setClients(p=>p.map(c=>c.id===id?{...c,stage}:c));if(sel?.id===id)setSel(s=>({...s,stage}));};
  const ff=k=>v=>setForm(f=>({...f,[k]:v}));
  const filtered=clients.filter(c=>{const q=search.toLowerCase();return(!q||c.name.toLowerCase().includes(q)||(c.phone||"").includes(q))&&(fs==="Todos"||c.stage===fs);});
  const stats={total:clients.length,active:clients.filter(c=>c.stage==="Cliente ativo").length,leads:clients.filter(c=>c.stage==="Lead").length,fup:clients.filter(c=>c.stage==="FUP").length,att:clients.reduce((s,c)=>s+(c.attendances||[]).length,0),pend:clients.reduce((s,c)=>s+(c.tasks||[]).filter(t=>!t.done).length,0)};

  if(loading)return <div style={{display:"flex",alignItems:"center",justifyContent:"center",height:"100vh",color:navy,fontFamily:"sans-serif",background:cream}}>Carregando e.Health CRM…</div>;

  return(<div style={{fontFamily:"'Segoe UI',sans-serif",background:cream,minHeight:"100vh"}}>
    <div style={{background:navy,padding:"16px 24px",display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:10}}>
      <div><div style={{color:gold,fontWeight:700,fontSize:20}}>e.Health</div><div style={{color:"#aab8c2",fontSize:12}}>CRM Interno</div></div>
      <div style={{display:"flex",gap:8}}>{[["list","Lista"],["kanban","Funil"],["dashboard","Painel"]].map(([v,l])=><button key={v} onClick={()=>setView(v)} style={{padding:"6px 14px",borderRadius:20,border:"none",cursor:"pointer",background:view===v?gold:"transparent",color:view===v?navy:"#aab8c2",fontWeight:600,fontSize:13}}>{l}</button>)}</div>
      <button onClick={()=>{setForm({...E0});setModal("form");}} style={{background:gold,color:navy,border:"none",borderRadius:8,padding:"8px 18px",fontWeight:700,fontSize:14,cursor:"pointer"}}>+ Nova Cliente</button>
    </div>

    {view==="list"&&<div style={{padding:24}}>
      <div style={{display:"flex",gap:12,marginBottom:20,flexWrap:"wrap"}}>
        <input placeholder="Buscar…" value={search} onChange={e=>setSearch(e.target.value)} style={{flex:1,minWidth:200,padding:"9px 14px",border:"1px solid #c9b89a",borderRadius:8,fontSize:14,background:"#fffdf8",outline:"none"}}/>
        <select value={fs} onChange={e=>setFs(e.target.value)} style={{padding:"9px 14px",border:"1px solid #c9b89a",borderRadius:8,fontSize:14,background:"#fffdf8",outline:"none"}}><option value="Todos">Todos</option>{STAGES.map(s=><option key={s}>{s}</option>)}</select>
      </div>
      {filtered.length===0?<div style={{textAlign:"center",padding:48,color:"#aaa"}}><div style={{fontSize:40,marginBottom:12}}>👤</div><div>Nenhuma cliente.</div><button onClick={()=>{setForm({...E0});setModal("form");}} style={{marginTop:16,background:gold,color:navy,border:"none",borderRadius:8,padding:"8px 20px",fontWeight:700,cursor:"pointer"}}>Adicionar</button></div>
      :filtered.map(c=>{const pend=(c.tasks||[]).filter(t=>!t.done).length;return <div key={c.id} onClick={()=>{setSel(c);setTab("geral");setModal("detail");}} style={{background:"#fff",borderRadius:12,padding:"13px 18px",display:"flex",alignItems:"center",gap:14,boxShadow:"0 1px 4px #0001",border:"1px solid #e8dfc8",cursor:"pointer",marginBottom:8}}><div style={{width:40,height:40,borderRadius:"50%",background:navy,display:"flex",alignItems:"center",justifyContent:"center",color:gold,fontWeight:700,fontSize:15,flexShrink:0}}>{(c.name||"?")[0].toUpperCase()}</div><div style={{flex:1,minWidth:0}}><div style={{fontWeight:600,fontSize:14,color:navy}}>{c.name}</div><div style={{fontSize:12,color:"#888",marginTop:1}}>{locLabel(c.location)}{c.phone?" · "+c.phone:""}</div></div><div style={{display:"flex",gap:8,alignItems:"center",flexShrink:0}}>{pend>0&&<span style={{fontSize:12,color:"#7a3b8a",fontWeight:600}}>📋 {pend}</span>}<Badge stage={c.stage}/></div></div>;})}
    </div>}

    {view==="kanban"&&<div style={{padding:24,overflowX:"auto"}}><div style={{display:"flex",gap:12,minWidth:980}}>{STAGES.map(stage=>{const cols=clients.filter(c=>c.stage===stage);return <div key={stage} style={{flex:1,minWidth:150}}><div style={{background:COLORS[stage]+"22",borderRadius:10,padding:"7px 12px",marginBottom:10,borderTop:"3px solid "+COLORS[stage]}}><span style={{fontWeight:700,fontSize:12,color:COLORS[stage]}}>{stage}</span><span style={{marginLeft:6,fontSize:11,color:"#888"}}>{cols.length}</span></div>{cols.map(c=><div key={c.id} onClick={()=>{setSel(c);setTab("geral");setModal("detail");}} style={{background:"#fff",borderRadius:10,padding:"11px 13px",marginBottom:7,cursor:"pointer",border:"1px solid #e8dfc8"}}><div style={{fontWeight:600,fontSize:13,color:navy}}>{c.name}</div><div style={{fontSize:11,color:"#888",marginTop:3}}>{locLabel(c.location)}</div></div>)}</div>;})} </div></div>}

    {view==="dashboard"&&<div style={{padding:24}}>
      <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:14,marginBottom:20}}>{[{l:"Total",v:stats.total,c:navy},{l:"Ativas",v:stats.active,c:"#2d7a4f"},{l:"FUP",v:stats.fup,c:"#b05e1a"},{l:"Leads",v:stats.leads,c:gold},{l:"Atendimentos",v:stats.att,c:"#2a6b8a"},{l:"Tarefas pendentes",v:stats.pend,c:"#7a3b8a"}].map(s=><div key={s.l} style={{background:"#fff",borderRadius:12,padding:"16px 18px",borderLeft:"4px solid "+s.c,boxShadow:"0 2px 8px #0001"}}><div style={{fontSize:26,fontWeight:700,color:s.c}}>{s.v}</div><div style={{fontSize:12,color:"#888",marginTop:2}}>{s.l}</div></div>)}</div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
        <div style={{background:"#fff",borderRadius:12,padding:20}}><div style={{fontWeight:700,marginBottom:14,color:navy}}>Funil</div>{STAGES.map(st=>{const n=clients.filter(c=>c.stage===st).length,pct=clients.length?Math.round(n/clients.length*100):0;return <div key={st} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:3}}><span>{st}</span><span style={{fontWeight:600}}>{n}</span></div><div style={{background:"#eee",borderRadius:4,height:7}}><div style={{width:pct+"%",background:COLORS[st],height:7,borderRadius:4}}/></div></div>;})}</div>
        <div style={{background:"#fff",borderRadius:12,padding:20}}><div style={{fontWeight:700,marginBottom:14,color:navy}}>Serviços</div>{SERVICES.map(sv=>{const n=clients.filter(c=>(c.services||[]).includes(sv)).length,pct=clients.length?Math.round(n/clients.length*100):0;return <div key={sv} style={{marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:3}}><span>{sv}</span><span style={{fontWeight:600}}>{n}</span></div><div style={{background:"#eee",borderRadius:4,height:7}}><div style={{width:pct+"%",background:gold,height:7,borderRadius:4}}/></div></div>;})}</div>
      </div>
    </div>}

    {modal==="form"&&<Modal title={form.id?"Editar Cliente":"Nova Cliente"} onClose={()=>setModal(null)}>
      <Inp label="Nome *" value={form.name} onChange={ff("name")}/>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><Inp label="Telefone" value={form.phone} onChange={ff("phone")} placeholder="(11) 99999-9999"/><Inp label="Aniversário" value={form.birthday||""} onChange={ff("birthday")} type="date"/></div>
      <Inp label="E-mail" value={form.email} onChange={ff("email")} type="email"/>
      <Sel label="Funil" value={form.stage} onChange={ff("stage")} options={STAGES}/>
      <div style={{marginBottom:13}}><label style={{display:"block",fontSize:12,fontWeight:600,marginBottom:6}}>Local</label><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{LOCATIONS.map(loc=><button key={loc} onClick={()=>ff("location")(loc)} style={{flex:1,minWidth:110,padding:"7px 0",borderRadius:8,border:"2px solid",borderColor:form.location===loc?gold:"#c9b89a",background:form.location===loc?gold+"22":"#fffdf8",fontWeight:form.location===loc?700:400,fontSize:12,cursor:"pointer"}}>{locLabel(loc)}</button>)}</div></div>
      <MC label="Serviços" options={SERVICES} selected={form.services||[]} onChange={ff("services")}/>
      <TA label="Observações" value={form.notes} onChange={ff("notes")}/>
      <div style={{display:"flex",gap:10,marginTop:4}}><button onClick={upsert} disabled={!form.name} style={{flex:1,background:navy,color:gold,border:"none",borderRadius:8,padding:"10px 0",fontWeight:700,fontSize:15,cursor:"pointer"}}>Salvar</button>{form.id&&<button onClick={()=>del(form.id)} style={{background:"#fee",color:"#c0392b",border:"1px solid #fcc",borderRadius:8,padding:"10px 16px",cursor:"pointer",fontWeight:600}}>Excluir</button>}</div>
    </Modal>}

    {modal==="detail"&&sel&&<Modal title={sel.name} onClose={()=>setModal(null)} wide>
      <div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap"}}><Badge stage={sel.stage}/><span style={{background:gold+"22",color:"#7a5c1e",border:"1px solid "+gold+"66",borderRadius:20,padding:"2px 10px",fontSize:12,fontWeight:600}}>{locLabel(sel.location)}</span>{(sel.services||[]).map(s=><span key={s} style={{background:"#f0ebe0",borderRadius:20,padding:"2px 10px",fontSize:12,border:"1px solid #ddd"}}>{s}</span>)}</div>
      <div style={{marginBottom:14}}><div style={{fontSize:12,fontWeight:600,color:"#888",marginBottom:6}}>Mover no funil</div><div style={{display:"flex",flexWrap:"wrap",gap:5}}>{STAGES.map(st=><button key={st} onClick={()=>mv(sel.id,st)} style={{padding:"4px 11px",borderRadius:20,border:"1px solid",borderColor:sel.stage===st?COLORS[st]:"#ddd",background:sel.stage===st?COLORS[st]+"22":"#fff",color:sel.stage===st?COLORS[st]:"#888",fontSize:12,cursor:"pointer",fontWeight:sel.stage===st?700:400}}>{st}</button>)}</div></div>
      <Tabs active={tab} onChange={setTab} tabs={[{id:"geral",label:"Visão geral"},{id:"tarefas",label:"Tarefas"+((sel.tasks||[]).filter(t=>!t.done).length>0?" ("+((sel.tasks||[]).filter(t=>!t.done).length)+")":"")},{id:"touchpoints",label:"Touch points ("+(sel.touchpoints||[]).length+")"},{id:"atendimentos",label:"Atendimentos ("+(sel.attendances||[]).length+")"}]}/>
      {tab==="geral"&&<div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,fontSize:13,marginBottom:14}}>{sel.phone&&<div><span style={{color:"#888"}}>Tel: </span>{sel.phone}</div>}{sel.email&&<div><span style={{color:"#888"}}>Email: </span>{sel.email}</div>}{sel.birthday&&<div><span style={{color:"#888"}}>Aniversário: </span>{new Date(sel.birthday+"T12:00:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"long"})}</div>}</div>{sel.notes&&<div style={{background:"#f8f3ea",borderRadius:8,padding:"10px 12px",fontSize:13,color:"#555"}}>{sel.notes}</div>}<button onClick={()=>{setForm({...sel});setModal("form");}} style={{marginTop:16,width:"100%",background:navy,color:gold,border:"none",borderRadius:8,padding:"9px 0",fontWeight:700,cursor:"pointer"}}>Editar</button></div>}
      {tab==="tarefas"&&<div><button onClick={()=>{setTf({title:"",dueDate:"",reminder:"",done:false});setSub("task");}} style={{background:gold,color:navy,border:"none",borderRadius:8,padding:"7px 16px",fontSize:13,fontWeight:700,cursor:"pointer",marginBottom:14}}>+ Nova tarefa</button>{(sel.tasks||[]).length===0?<div style={{fontSize:13,color:"#aaa",textAlign:"center",padding:"16px 0"}}>Nenhuma tarefa.</div>:(sel.tasks||[]).map(t=>{const ov=!t.done&&t.dueDate&&new Date(t.dueDate+"T12:00:00")<new Date();return <div key={t.id} style={{display:"flex",alignItems:"flex-start",gap:10,padding:"10px 12px",background:t.done?"#f0f0f0":ov?"#fff3ee":"#fff",borderRadius:8,border:"1px solid "+(ov&&!t.done?"#f0a070":"#e8dfc8"),marginBottom:8}}><button onClick={()=>upd(c=>({...c,tasks:(c.tasks||[]).map(x=>x.id===t.id?{...x,done:!x.done}:x)}))} style={{width:20,height:20,borderRadius:4,border:"2px solid "+(t.done?"#2d7a4f":"#c9b89a"),background:t.done?"#2d7a4f":"transparent",cursor:"pointer",flexShrink:0,display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",fontSize:12,marginTop:1}}>{t.done?"✓":""}</button><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:t.done?"#aaa":navy,textDecoration:t.done?"line-through":"none"}}>{t.title}</div>{t.dueDate&&<div style={{fontSize:12,color:ov&&!t.done?"#b05e1a":"#888",marginTop:2}}>📅 {new Date(t.dueDate+"T12:00:00").toLocaleDateString("pt-BR")}</div>}</div><button onClick={()=>upd(c=>({...c,tasks:(c.tasks||[]).filter(x=>x.id!==t.id)}))} style={{background:"none",border:"none",color:"#ccc",cursor:"pointer",fontSize:16}}>×</button></div>;})}</div>}
      {tab==="touchpoints"&&<div><button onClick={()=>{setPf({date:new Date().toISOString().split("T")[0],channel:"WhatsApp",direction:"Entrada",summary:""});setSub("touch");}} style={{background:gold,color:navy,border:"none",borderRadius:8,padding:"7px 16px",fontSize:13,fontWeight:700,cursor:"pointer",marginBottom:14}}>+ Registrar contato</button>{(sel.touchpoints||[]).length===0?<div style={{fontSize:13,color:"#aaa",textAlign:"center",padding:"16px 0"}}>Nenhum touch point.</div>:(sel.touchpoints||[]).map(tp=><div key={tp.id} style={{display:"flex",gap:10,padding:"10px 12px",background:"#fff",borderRadius:8,border:"1px solid #e8dfc8",marginBottom:8}}><div style={{width:36,height:36,borderRadius:"50%",background:gold+"22",display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,flexShrink:0}}>{tp.channel==="WhatsApp"?"💬":"🤝"}</div><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:2}}><span style={{fontWeight:600,fontSize:13,color:navy}}>{tp.channel} · {tp.direction}</span><span style={{fontSize:12,color:"#aaa"}}>{tp.date?new Date(tp.date+"T12:00:00").toLocaleDateString("pt-BR"):""}</span></div><div style={{fontSize:13,color:"#555"}}>{tp.summary}</div></div></div>)}</div>}
      {tab==="atendimentos"&&<div><button onClick={()=>{setAf({date:"",service:"",professional:"",notes:"",duration:""});setSub("att");}} style={{background:gold,color:navy,border:"none",borderRadius:8,padding:"7px 16px",fontSize:13,fontWeight:700,cursor:"pointer",marginBottom:14}}>+ Registrar atendimento</button>{(sel.attendances||[]).length===0?<div style={{fontSize:13,color:"#aaa",textAlign:"center",padding:"16px 0"}}>Nenhum atendimento.</div>:(sel.attendances||[]).map(a=><div key={a.id} style={{background:"#f8f3ea",borderRadius:8,padding:"10px 12px",fontSize:13,marginBottom:8}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:3}}><span style={{fontWeight:600,color:navy}}>{a.service}</span><span style={{color:"#888"}}>{a.date?new Date(a.date+"T12:00:00").toLocaleDateString("pt-BR"):""}{a.duration?" · "+a.duration+"min":""}</span></div>{a.professional&&<div style={{color:"#888"}}>Prof: {a.professional}</div>}{a.notes&&<div style={{color:"#555",marginTop:2}}>{a.notes}</div>}</div>)}</div>}
    </Modal>}

    {sub==="task"&&<Modal title="Nova Tarefa" onClose={()=>setSub(null)}><Inp label="Descrição *" value={tf.title} onChange={v=>setTf(f=>({...f,title:v}))} placeholder="Ex: Ligar para confirmar"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><Inp label="Data limite" value={tf.dueDate} onChange={v=>setTf(f=>({...f,dueDate:v}))} type="date"/><Inp label="Lembrete" value={tf.reminder} onChange={v=>setTf(f=>({...f,reminder:v}))} type="date"/></div><button onClick={async()=>{if(!tf.title)return;await upd(c=>({...c,tasks:[{...tf,id:Date.now().toString(),done:false},...(c.tasks||[])]}));setTf({title:"",dueDate:"",reminder:"",done:false});setSub(null);}} disabled={!tf.title} style={{width:"100%",background:navy,color:gold,border:"none",borderRadius:8,padding:"10px 0",fontWeight:700,cursor:"pointer",marginTop:4}}>Salvar</button></Modal>}
    {sub==="touch"&&<Modal title="Touch Point" onClose={()=>setSub(null)}><Inp label="Data" value={pf.date} onChange={v=>setPf(f=>({...f,date:v}))} type="date"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><Sel label="Canal" value={pf.channel} onChange={v=>setPf(f=>({...f,channel:v}))} options={["WhatsApp","Presencial"]}/><Sel label="Direção" value={pf.direction} onChange={v=>setPf(f=>({...f,direction:v}))} options={["Entrada","Saída"]}/></div><TA label="Resumo *" value={pf.summary} onChange={v=>setPf(f=>({...f,summary:v}))}/><button onClick={async()=>{if(!pf.summary)return;await upd(c=>({...c,touchpoints:[{...pf,id:Date.now().toString()},...(c.touchpoints||[])]}));setPf({date:"",channel:"WhatsApp",direction:"Entrada",summary:""});setSub(null);}} disabled={!pf.summary} style={{width:"100%",background:navy,color:gold,border:"none",borderRadius:8,padding:"10px 0",fontWeight:700,cursor:"pointer",marginTop:4}}>Salvar</button></Modal>}
    {sub==="att"&&<Modal title="Atendimento" onClose={()=>setSub(null)}><Inp label="Data" value={af.date} onChange={v=>setAf(f=>({...f,date:v}))} type="date"/><Sel label="Serviço" value={af.service||SERVICES[0]} onChange={v=>setAf(f=>({...f,service:v}))} options={SERVICES}/><Inp label="Profissional" value={af.professional} onChange={v=>setAf(f=>({...f,professional:v}))} placeholder="Nome"/><Inp label="Duração (min)" value={af.duration} onChange={v=>setAf(f=>({...f,duration:v}))} type="number"/><TA label="Observações" value={af.notes} onChange={v=>setAf(f=>({...f,notes:v}))}/><button onClick={async()=>{await upd(c=>({...c,attendances:[{...af,id:Date.now().toString()},...(c.attendances||[])]}));setAf({date:"",service:"",professional:"",notes:"",duration:""});setSub(null);}} style={{width:"100%",background:navy,color:gold,border:"none",borderRadius:8,padding:"10px 0",fontWeight:700,cursor:"pointer",marginTop:4}}>Salvar</button></Modal>}
  </div>);
}